version: '3.8'
services:
  reddit-to-tiktok:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    restart: no